version: 2

sources:
  - name: atlas
    schema: "source__{{ env_var('MERCHANT') }}"

    tables:
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: serving_date
            tests:
              - not_null